### ISSUE TITLE
PyQt4 Errors

### ISSUE THREAD

**Issue by ttepatti** [SECFORCE/sparta#77]
Hello,

I'm currently on Debian Stretch and it appears that the PyQt4 issues referenced back in Issue #59 are still causing problems.

This system already has the latest python-qt4 along with all other suggested Sparta dependencies.

`[-] Import failed. PyQt4 library not found.
Try installing it with: apt-get install python-qt4`

I tried installing Sparta today on Debian Stretch with the latest python-qt4 package installed to no avail.

My uname -a:
`Linux dpt 4.9.0-3-amd64 #1 SMP Debian 4.9.3-2+deb9u5 (2017-09-19) x86_64 GNU/Linux`

If anyone has any suggestions or fixes for this, they would be greatly appreciated. I saw users previously mentioning that Sparta should be upgraded to Qt5 - was that never carried out?

Thanks!

- Tim

**Comment by st3r30byt3** [comment]
Hi Tim,

Unfortunately, we haven't moved to Qt5 yet. In fact, we haven't had time to work on Sparta for a while. Also, due to lack of time and resources we focus mostly on making it work in Kali.

I'll leave this open in case anyone using Debian has any solution for you.

Thanks

**Comment by mrosenhahn** [comment]
I ran into this issue also.

It seems this is a recurring issue with Sparta.

I found an older post with a temp fix here:
https://github.com/SECFORCE/sparta/issues/59
and here
https://stackoverflow.com/questions/37604532/python-2-7-11-importerror-cannot-import-name-qtwebkit-kali-linux-debian-8

I tested the fix and it fixed the issue on my end.

**Comment by st3r30byt3** [comment]
This should be fixed in the latest commit. Thanks for the report. Thanks alexxn for the fix.

**Comment by shizzz477** [comment]
Still an issue with the latest Kali.  I installed PyQt4 from source which fixed it:
https://www.riverbankcomputing.com/software/pyqt/download
